"""Verify the shared input contract across built-in generators."""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Protocol, cast

import pytest

from generator.core.models import GenerateRequest, GenerationResult, RuntimeOptions
from generator.generators.bootstrap_generator import BootstrapGenerator
from generator.generators.course_generator import CourseGenerator
from generator.generators.week_generator import WeekGenerator


class Generator(Protocol):
    """Describe the canonical generator interface under test."""

    name: str

    def generate(self, request: GenerateRequest) -> GenerationResult:
        """Generate content from one immutable request."""
        ...

    def run(self, request: GenerateRequest) -> GenerationResult:
        """Run the complete generation lifecycle for one request."""
        ...


@dataclass(frozen=True, slots=True)
class GeneratorCase:
    """Define one built-in generator input-contract scenario."""

    name: str
    factory: Callable[[Path, Path], Generator]
    values: dict[str, object]
    templates: tuple[str, ...]
    expected_paths: Callable[[Path], tuple[Path, ...]]


CASES = (
    GeneratorCase(
        name="bootstrap",
        factory=lambda templates, target: BootstrapGenerator(templates, target),
        values={"project_slug": "input-contract-course"},
        templates=tuple(BootstrapGenerator.TEMPLATE_MANIFEST.values()),
        expected_paths=lambda target: tuple(
            target / "input-contract-course" / output_name
            for output_name in BootstrapGenerator.TEMPLATE_MANIFEST
        ),
    ),
    GeneratorCase(
        name="course",
        factory=lambda templates, target: CourseGenerator(templates, target),
        values={"course_name": "Input Contract Course"},
        templates=("course/README.md.j2",),
        expected_paths=lambda target: (target / "README.md",),
    ),
    GeneratorCase(
        name="week",
        factory=lambda templates, target: WeekGenerator(templates, target),
        values={"week": 1, "title": "Input Contract"},
        templates=("week/README.md.j2",),
        expected_paths=lambda target: (target / "week-01" / "README.md",),
    ),
)


@pytest.fixture(params=CASES, ids=lambda case: case.name)
def generator_case(request: pytest.FixtureRequest) -> GeneratorCase:
    """Return each built-in generator input-contract scenario."""
    return cast(GeneratorCase, request.param)


def _prepare_generator(
    tmp_path: Path,
    case: GeneratorCase,
) -> tuple[Generator, Path]:
    """Create minimal templates and a configured generator."""
    template_root = tmp_path / "templates"
    target = tmp_path / "output"

    for template_name in case.templates:
        template_path = template_root / template_name
        template_path.parent.mkdir(parents=True, exist_ok=True)
        template_path.write_text("generated by input contract test\n", encoding="utf-8")

    return case.factory(template_root, target), target


def _make_request(
    case: GeneratorCase,
    target: Path,
    *,
    dry_run: bool,
) -> GenerateRequest:
    """Build the canonical request for a generator case."""
    return GenerateRequest(
        generator_name=case.name,
        target=target,
        values=case.values,
        options=RuntimeOptions(dry_run=dry_run),
    )


def test_generate_accepts_request_and_returns_shared_result(
    tmp_path: Path,
    generator_case: GeneratorCase,
) -> None:
    """Require every built-in generator to consume the canonical request."""
    generator, target = _prepare_generator(tmp_path, generator_case)
    request = _make_request(generator_case, target, dry_run=False)

    result = generator.generate(request)

    assert type(result) is GenerationResult
    assert result.generator_name == request.generator_name == generator.name
    assert result.affected_paths == generator_case.expected_paths(target)
    assert result.dry_run is False


def test_run_accepts_request_and_returns_shared_result(
    tmp_path: Path,
    generator_case: GeneratorCase,
) -> None:
    """Require the public lifecycle entry point to consume the same request."""
    generator, target = _prepare_generator(tmp_path, generator_case)
    request = _make_request(generator_case, target, dry_run=True)

    result = generator.run(request)

    assert type(result) is GenerationResult
    assert result.generator_name == request.generator_name
    assert result.affected_paths == generator_case.expected_paths(target)
    assert result.dry_run is True


def test_request_remains_unchanged_after_generation(
    tmp_path: Path,
    generator_case: GeneratorCase,
) -> None:
    """Require generators to derive state without mutating request values."""
    generator, target = _prepare_generator(tmp_path, generator_case)
    original_values = dict(generator_case.values)
    request = _make_request(generator_case, target, dry_run=True)

    generator.generate(request)

    assert request.generator_name == generator_case.name
    assert request.target == target
    assert dict(request.values) == original_values
    assert request.options == RuntimeOptions(dry_run=True)
    assert generator_case.values == original_values


def test_dry_run_uses_request_options_without_filesystem_changes(
    tmp_path: Path,
    generator_case: GeneratorCase,
) -> None:
    """Require request options to control dry-run behavior consistently."""
    generator, target = _prepare_generator(tmp_path, generator_case)
    request = _make_request(generator_case, target, dry_run=True)

    result = generator.generate(request)

    assert result.dry_run is True
    assert result.manifest_updated is False
    assert result.affected_paths == generator_case.expected_paths(target)
    assert not target.exists()


def test_generator_name_mismatch_is_rejected(
    tmp_path: Path,
    generator_case: GeneratorCase,
) -> None:
    """Require each generator to reject requests addressed to another name."""
    generator, target = _prepare_generator(tmp_path, generator_case)
    request = GenerateRequest(
        generator_name=f"not-{generator_case.name}",
        target=target,
        values=generator_case.values,
        options=RuntimeOptions(dry_run=True),
    )

    with pytest.raises(ValueError, match="generator"):
        generator.generate(request)
